# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4887d29a65c046ca440578e4c6afc7a21f536734aa4055bac566fd706ae4168b6196dafc6335057000b6e5e9640b998501c09dc8a5d4735069ad6b63ef035b0e

test:
  secret_key_base: 94072d9289f3986901e790b54fc69da27994e6a6cdbb9ba47aa46db3757868eeac39946a99c88d54266d6c3945bfb2fc42b2037f4e1d61bf90c5f417ad106e15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
